### ISSUE TITLE
Add support for custom engine option on nodes

### ISSUE THREAD

**Issue by dduportal** [xinity/swarmt#9]
Use case: running a local private registry, with no SSL (by IP, or by domain name not resolvable publically) .

I launch `docker service create --name registry --publish 5000:5000 registry:2`, and then I want my nodes to be able to push/pull images on that private insecure registry.
I was planning to auto-launch a stack using your script awesome functionality :)

So I need to be able to add the `--engine-insecure-registry ${IP}:${PORT}` option for example.

If we generalize, One would want to pass option at init.

What do you think about adding option to the conf file for that ?

**Comment by xinity** [comment]
Great idea indeed!

Config file should be kept to the minimum but we can indeed document extended possibilities like :
`engineopt=`

Let's add this for the 0.2 release :-)

**Comment by xinity** [comment]
first implementation is done in 0.2 branch :)
